pkg [-v] [-d] [-l]	[-N] 	 [-j | -c | -r ] 	 [-C ] [-R ] 	 [-4 | -6] pkg [--version] [--debug] [--list]	[-N] 	 [--jail | --chroot | --rootdir	] 	 [--config ] 	 [--repo-conf-dir ]	[-4 | -6] 	 
pkg [-v] [-d] [-l]	[-N] 	 [-j | -c | -r ] 	 [-C ] [-R ] 	 [-4 | -6] pkg [--version] [--debug] [--list]	[-N] 	 [--jail | --chroot | --rootdir	] 	 [--config ] 	 [--repo-conf-dir ]	[-4 | -6] 	 
The following options are supported by pkg: -v, --version 	 Display the current version of pkg. -d, --debug 	 Show debug	information. -l, --list 	 List all the available command names, and exit without performing 	 any other action.	The -v option takes precedence over -l but -l 	 will override any other command line arguments. -o	,	--option 	 Set configuration option for pkg from the command line. Options 	 that are set from the environment are redefined. It is permitted 	 to	specify	this option multiple times. -N	 Activation	status check mode. Prevent pkg	from automatically 	 creating or initializing the SQLite database in 	 /var/db/pkg/local.sqlite if it does not already exist. 	 Prevent pkg from performing any actions if	no packages are	cur- 	 rently installed, on the basis that a correctly initialised sys- 	 tem using pkg will	always have at least the pkg package itself 	 registered. 	 If	used without any other arguments, pkg -N will run the sanity 	 tests and if successful print out a short message showing how 	 many packages are currently installed. The exit status should be 	 a reliable	indication of whether a	system is configured to	use 	 pkg as its	package	management system or not. 	 Example usage: 		 if	pkg -N >/dev/null 2>&1;	then 		 # pkgng-specifics 		 else 		 # pkg_install-specifics 		 fi 	 The -N flag was first released in the /usr/sbin/pkg bootstrapper 	 in	FreeBSD	8.4, but was missing from FreeBSD 9.1.	It may not be 	 enough to just call pkg -N, as the	bootstrapper may be invoked, 	 or	an error returned from pkg. The following script is the 	 safest way	to detect if pkg is installed and activated: 		 if	TMPDIR=/dev/null ASSUME_ALWAYS_YES=yes \ 			 PACKAGESITE=file:///nonexistent \ 			 pkg info -x 'pkg(-devel)?$' >/dev/null 2>&1; then 		 # pkgng-specifics 		 else 		 # pkg_install-specifics 		 fi -j	, --jail 	 pkg will execute in the given , where name 	 matches ``jls name'' and id matches ``jls jid''. See jail(8) and 	 jls(8). -c	, --chroot	 	 pkg wi
re should be taken when using this command. shlib Displays which packages link to a specific	shared library. stats Display package database statistics. unlock Unlocks packages, allowing	them to	be modified or deleted. update Update the	available remote repositories as listed	in 	 pkg.conf(5). updating 	 Display UPDATING entries of installed packages. upgrade 	 Upgrade a package to a newer version. version 	 Summarize installed versions of packages. which Query the database	for package(s) that installed a	specific file. 
All configuration options from pkg.conf.5 can be passed as	environment variables. Extra environment variables are: INSTALL_AS_USER Allow to do all manipulation as a	regular	user instead 		 of checking for root credentials when appropriate. 		 It is expected that the user will	ensure that every file 		 and directory manipulated	by pkg are readable (or 		 writable where appropriate) by the user. 
See pkg.conf(5).
Search for	a package: 	 $ pkg search	perl Install a package: 	 Installing must specify a unique origin or version otherwise	it 	 will	try installing all matches. 	 % pkg install perl-5.14 List installed packages: 	 $ pkg info Upgrade from remote repository: 	 % pkg upgrade Change the	origin for an installed	package: 	 % pkg set -o	lang/perl5.12:lang/perl5.14 	 % pkg install -Rf lang/perl5.14 List non-automatic	packages: 	 $ pkg query -e '%a =	0' %o List automatic packages: 	 $ pkg query -e '%a =	1' %o Delete an installed package: 	 % pkg delete	perl-5.14 Remove unneeded dependencies: 	 % pkg autoremove Change a package from automatic to	non-automatic, which will prevent autoremove	from removing it: 	 % pkg set -A	0 perl-5.14 Change a package from non-automatic to automatic, which will make autoremove	allow it be removed once nothing depends on it: 	 % pkg set -A	1 perl-5.14 Create package file from an installed package: 	 % pkg create	-o /usr/ports/packages/All perl-5.14 Determine which package installed a file: 	 $ pkg which /usr/local/bin/perl Audit installed packages for security advisories: 	 $ pkg audit Check installed packages for checksum mismatches: 	 # pkg check -s -a Check for missing dependencies: 	 # pkg check -d -a
QTu12SdX7VM
Baptiste Daroussin	, Julien Laffaye , Philippe Pepiot , Will Andrews , Marin Atanasov Nikolov , Yuri Pankov , Alberto Villa , Brad Davis	, Matthew Seaman , Bryan Drewery , Eitan Adler , Romain Tarti`ere , Vsevolod Stakhov , Alexandre Perrin 
See the issue tracker at https://github.com/freebsd/pkg/issues Please direct questions and issues	to the pkg@FreeBSD.org mailing list.
